_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 79
            "2":
                - 1
                - 5
                - 53
                - 55
                - 79
            "3":
                - 2
                - 23
                - 55
            "4": 3.10.16
            "5": 0.18.0
            "8":
                - 1
                - 5
            "12": 0.18.0
            "13": linux-x86_64
Training Set Size:
    value: 2
Validation Set Size:
    value: 3
