_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 79
            "2":
                - 1
                - 5
                - 53
                - 55
                - 79
            "3":
                - 23
                - 55
                - 61
            "4": 3.10.16
            "5": 0.18.0
            "8":
                - 5
            "12": 0.18.0
            "13": linux-x86_64
Deep Supervision:
    value: true
Model:
    value: nnUnet
Training Set Size:
    value: 600
Validation Set Size:
    value: 200
initial_lr:
    value: 0.01
loss_fn:
    value: mse
num_epochs:
    value: 1000
'num_iters_per_epoch ':
    value: 400
num_val_iters_per_epoch:
    value: 100
weight_decay:
    value: 3e-05
